### ISSUE TITLE
Cannot use the EventPublisher in a symfony application

### ISSUE THREAD

**Issue by yvoyer** [yvoyer/domain-event#9]
I get an error `must be an instance of MyApp\Event instance of Star\Component\DomainEvent\Symfony\EventAdapter given` when using the symfony dispatcher in my app.

```
// services.yml
services:
    app.event_publisher:
        class: Star\Component\DomainEvent\Symfony\SymfonyPublisher
        arguments:
            - '@event_dispatcher'

    MyApp\MyListener:
        tags:
            - { name: 'kernel.event_subscriber' }
```
